name: Pruebas de integración PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: sistema_envios
          MYSQL_USER: devops
          MYSQL_PASSWORD: devops123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar PHP y cliente MySQL
        run: |
          sudo apt update
          sudo apt install -y php php-mysql mysql-client

      - name: Importar base de datos
        run: |
          mysql -h 127.0.0.1 -u devops -pdevops123 < database/database.sql

      - name: Validar base de datos
        run: |
          mysql -h 127.0.0.1 -u devops -pdevops123 -e "SHOW DATABASES;"
          mysql -h 127.0.0.1 -u devops -pdevops123 -e "USE sistema_envios; SHOW TABLES;"

      - name: Ejecutar test login admin
        run: |
          php test/integration/test_login.php

      - name: Ejecutar test insertar envío
        run: |
          php test/integration/test_insert_envio.php
